# Generated by Django 5.2.9 on 2026-04-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_ingredients', models.TextField(blank=True, null=True)),
                ('how_to_use', models.TextField(blank=True, null=True)),
                ('key_benefits', models.TextField(blank=True, null=True)),
                ('title_arabic', models.CharField(max_length=255)),
                ('sub_title_arabic', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_type_arabic', models.CharField(blank=True, max_length=100, null=True)),
                ('description_arabic', models.TextField()),
                ('key_ingredients_arabic', models.TextField(blank=True, null=True)),
                ('how_to_use_arabic', models.TextField(blank=True, null=True)),
                ('key_benefits_arabic', models.TextField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage or amount', max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
